name: InputGuard
options:
  bundleIdPrefix: com.brendonovich
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.9.4
targets:
  InputGuard:
    type: application
    platform: macOS
    sources:
      - InputGuard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brendonovich.InputGuard
        PRODUCT_NAME: Input Guard
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: InputGuard/Info.plist
        CODE_SIGN_STYLE: Automatic
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: YES
        DEAD_CODE_STRIPPING: YES
    dependencies:
      - package: Sparkle
      - sdk: CoreAudio.framework
      - sdk: ServiceManagement.framework
