name: BatteryWatch
options:
  bundleIdPrefix: com.brendonovich
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  BatteryWatch:
    type: application
    platform: macOS
    sources:
      - BatteryWatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brendonovich.BatteryWatch
        PRODUCT_NAME: Battery Watch
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: BatteryWatch/Info.plist
        CODE_SIGN_STYLE: Automatic
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: YES
        DEAD_CODE_STRIPPING: YES
    dependencies:
      - sdk: ServiceManagement.framework
      - sdk: UserNotifications.framework
